### ISSUE TITLE
Add option to switch a/b buttons

### ISSUE THREAD

**Issue by dskmusic** [cizia64/CrossMix-OS#111] opened 2024-07-18 21:32 UTC
would be a nice addition :)

**Comment by cizia64** [comment] 2024-07-18 21:49
Switch it where ? It's already possible in retroarch menu.
In TrimUI MainUI it requires some tricks. I achieved it recently with gptokeyb binary so it's in the roadmap.


(Duplicate of https://github.com/cizia64/CrossMix-OS/issues/24)

**Comment by nngw-ep** [comment] 2024-09-03 06:45
Yes please, I'm really getting confused with Nintendo-style OS controls, especially since I can switch my Android handheld to Xbox mode luckily :-)

**Comment by cizia64** [comment] 2024-10-30 01:21
Will be implemented in CrossMix v1.3.0 : https://github.com/cizia64/CrossMix-OS/pull/147

**Closed by cizia64** 2024-10-30 01:21 UTC
