### ISSUE TITLE
Zip errors when extracting the asset

### ISSUE THREAD

**Issue by dmaysr** [cizia64/CrossMix-OS#1] opened 2024-06-03 02:13 UTC
See errors per 7 Zip:

Unsupported compression method : Apps\FileManager\lib\libSDL2_gfx-1.0.so.0
Unsupported compression method : Apps\FileManager\lib\libSDL2_image-2.0.so.0
Unsupported compression method : Apps\ScreencapTK\lib\libfdk-aac.so.2
Unsupported compression method : Apps\ScreencapTK\lib\libmp3lame.so.0
Unsupported compression method : Emus\PICO8_Wrapper\lib\libEGL.so.1
Unsupported compression method : Emus\PICO8_Wrapper\lib\libSDL2-2.0.so.0
Unsupported compression method : Emus\PICO8_Wrapper\lib\libSDL2_image-2.0.so.0
Unsupported compression method : RetroArch\.retroarch\cores\2048_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\81_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\DoubleCherryGB_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\a5200_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\arduous_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\atari800_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\bluemsx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\bnes_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\cannonball_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\cap32_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\chailove_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\craft_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\crocods_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\daphne_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\desmume2015_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\dinothawr_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\dosbox_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\dosbox_pure_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\dosbox_svn_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\duckstation_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\easyrpg_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\ecwolf_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\ep128emu_core_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fake08_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha2012_cps1_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha2012_cps2_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha2012_cps3_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha2012_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha2012_neogeo_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbalpha_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fbneo_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fceumm_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fceunext_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fly_flycast_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\flycast_libretro-old.so
Unsupported compression method : RetroArch\.retroarch\cores\flycast_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\flycast_rumble_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fmsx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\freechaf_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\freeintv_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\fuse_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gambatte_gb_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gambatte_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gearboy_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gearcoleco_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gearsystem_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\genesis_plus_gx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\genesis_plus_gx_wide_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\geolith_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gme_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gpsp_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\gw_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\handy_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\hatari_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\imageviewer_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\lowresnx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\lutro_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2000_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2003_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2003_plus_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2010_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2015_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame2016_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame219_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mame_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_gba_libretro_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_lynx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_ngp_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_pce_fast_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_pcfx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_supafaust_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_supergrafx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_vb_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mednafen_wswan_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\melonds_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mesen_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mess2015_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mess_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\meteor_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mgba_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mgba_rumble_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\minivmac_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mpv_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mrboom_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mu_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mupen64plus_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\mupen64plus_next_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\nekop2_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\neocd_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\nestopia_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\np2kai_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\numero_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\nxengine_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\o2em_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\onscripter_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\opera_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\parallel_n64_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\pcsx_rearmed_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\pcsx_rearmed_rumble_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\picodrive_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\pokemini_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\potator_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\ppsspp_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\prboom_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\prosystem_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\puae2021_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\puae_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\px68k_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\quasi88_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\quicknes_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\race_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\reminiscence_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\retro8_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\same_cdi_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\sameboy_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\sameduck_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\scummvm_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\scummvm_libretro1.so
Unsupported compression method : RetroArch\.retroarch\cores\snes9x2002_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\snes9x2005_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\snes9x2005_plus_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\snes9x2010_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\snes9x_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\stella2014_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\stella_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\superflappybirds_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\swanstation_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\tgbdual_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\theodore_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\tic80_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\tyrquake_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\uae4arm_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\uzem_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vba_next_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vbam_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vecx_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vemulator_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_x128_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_x64_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_x64sc_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xcbm2_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xcbm5x0_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xpet_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xplus4_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xscpu64_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\vice_xvic_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\virtualjaguar_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\wasm4_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\x1_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\xrick_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\yabasanshiro_libretro.so
Unsupported compression method : RetroArch\.retroarch\cores\yabause_libretro.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\aai.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\art.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\avs.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\bgr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\bmp.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\braille.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\cals.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\caption.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\cin.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\cip.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\clip.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\cmyk.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\cut.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dcm.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dds.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\debug.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dib.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dng.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dot.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\dpx.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ept.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\exr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\fax.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\fits.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\gif.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\gradient.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\gray.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\hald.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\hdr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\histogram.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\hrz.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\html.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\icon.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\info.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\inline.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ipl.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\jnx.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\jpeg.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\json.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\label.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mac.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\magick.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\map.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mask.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mat.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\matte.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\meta.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\miff.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mono.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mpc.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mpeg.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mpr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\msl.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mtv.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\mvg.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\null.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\otb.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\palm.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pango.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pattern.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pcd.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pcl.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pcx.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pdb.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pdf.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pes.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pgx.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pict.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pix.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\plasma.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\png.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pnm.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\preview.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ps.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ps2.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ps3.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\psd.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\pwp.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\raw.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\rgb.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\rgf.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\rla.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\rle.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\scr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\sct.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\sfw.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\sgi.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\sixel.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\stegano.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\sun.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\svg.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\tga.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\thumbnail.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\tiff.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\tile.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\tim.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ttf.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\txt.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\uil.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\url.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\uyvy.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\vicar.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\vid.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\viff.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\vips.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\wbmp.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\wmf.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\wpg.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\x.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xbm.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xc.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xcf.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xpm.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xps.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xtrn.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\xwd.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\ycbcr.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\coders\yuv.so
Unsupported compression method : System\bin\imagemagick\lib64\ImageMagick-6.9.10\modules-Q16\filters\analyze.so
Unsupported compression method : System\bin\imagemagick\lib64\libICE.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libMagickCore-6.Q16.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libMagickWand-6.Q16.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libSM.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libX11.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libXext.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libXt.so.6
Unsupported compression method : System\bin\imagemagick\lib64\libbz2.so.1
Unsupported compression method : System\bin\imagemagick\lib64\liblcms2.so.2
Unsupported compression method : System\bin\imagemagick\lib64\libltdl.so.7
Unsupported compression method : System\bin\imagemagick\lib64\libxcb.so.1
Unsupported compression method : System\lib\libFLAC.so.8
Unsupported compression method : System\lib\libGLX.so.0
Unsupported compression method : System\lib\libGLdispatch.so.0
Unsupported compression method : System\lib\libOpenGL.so.0
Unsupported compression method : System\lib\libSDL2_gfx-1.0.so.0
Unsupported compression method : System\lib\libSDL2_net-2.0.so.0
Unsupported compression method : System\lib\libX11.so.6
Unsupported compression method : System\lib\libXau.so.6
Unsupported compression method : System\lib\libavcodec.so.58
Unsupported compression method : System\lib\libcairo.so.2
Unsupported compression method : System\lib\libcrypto.so.1.1
Unsupported compression method : System\lib\libgraphite2.so.3
Unsupported compression method : System\lib\libharfbuzz.so.0
Unsupported compression method : System\lib\libidn2.so.0
Unsupported compression method : System\lib\libjpeg.so.62
Unsupported compression method : System\lib\libjpeg.so.8
Unsupported compression method : System\lib\liblcms2.so.2
Unsupported compression method : System\lib\liblzma.so.5
Unsupported compression method : System\lib\libmpg123.so.0
Unsupported compression method : System\lib\libmpv.so.1
Unsupported compression method : System\lib\libncurses.so.6
Unsupported compression method : System\lib\libncursesw.so.6
Unsupported compression method : System\lib\libnettle.so.8
Unsupported compression method : System\lib\libpcre2-8.so.0
Unsupported compression method : System\lib\libpng16.so.16
Unsupported compression method : System\lib\libreadline.so.7
Unsupported compression method : System\lib\libssl.so.1.1
Unsupported compression method : System\lib\libtinfo.so.6
Unsupported compression method : System\lib\libunistring.so.2
Unsupported compression method : System\lib\libxcb.so.1
Unsupported compression method : System\lib\libz.so.1
Unsupported compression method : System\lib\libzstd.so.1

**Comment by cizia64** [comment] 2024-06-03 02:18
For this first release, upgrade your 7zip if you have extraction problems, I will downgrade the 7zip version for the next release.

**Comment by dmaysr** [comment] 2024-06-03 02:20
Confirmed. 7 Zip version 24.06 extracts with no issue.

**Comment by 2Bane** [comment] 2024-06-05 10:18
Confirmed for Windows installs you should manually update 7z. This file requires at least v23.00 which released in 2023-05-07.

Linux installs its less likely to be out of date due to better package management.

**Comment by alexpvieira** [comment] 2024-06-10 06:50
I'm having similar problem on MacOS. Tried with the desktop version of Unarchiver and also the default MacOS one and p7zip terminal utility, all with no luck.

**Comment by cizia64** [comment] 2024-06-10 14:41
Will be solved in CrossMix 1.1.0, I hope to release it tomorrow ;)
I will create a zip archive, the compression will be a little less good but no compatibility problems at all.

**Comment by cizia64** [comment] 2024-06-14 01:45
CrossMix 1.1.0 released in zip file format, should be solved.

**Closed by cizia64** 2024-06-14 01:45 UTC
